### ISSUE TITLE
Should the Modal overlay be clickable?

### ISSUE THREAD

**Issue by bkemper** [SparkPost/matchbox#133]
This question comes from review feedback on https://github.com/SparkPost/2web2ui/pull/490.  Here is the original questions.

> Close button is good. However, the click-anywhere-to-close behaviour is a bit risky now. I can half-fill the form, accidentally click or hit escape and my form contents are lost.

**Comment by jonambas** [comment]
Yes, full screen takeovers should always be easy to escape from.

If closing the modal is "risky", perhaps consider creating another page for the support UI instead.
