### ISSUE TITLE
General feedbacks

### ISSUE THREAD

**Issue by rajumsys** [SparkPost/matchbox#134]
_i'll write feedbacks I get while I write tests in this issue_

- Banner component accepts both `action` and `actions` props. While no issue around that, I guess it just simpler to just use only one, that is `actions`. To simulate `action`, we'll just pass it in an array `[action]`. 
- Storybook for `DatePicker`
- `id` prop for `Label` is confusing. I thought it's ID of the label. I think just `for` or currently (internally) used name `htmlFor` will make more sense.

**Comment by jonambas** [comment]
+1 on the Banner props

We are getting rid of Datepicker from this library, we removed the story for now, but will need to transfer it to the UI

+1 on adjusting id for Label, will need to update the other components that use it
