### ISSUE TITLE
The Banner component needs `role="alert"`

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#192]
The [Banner Component](https://sparkpost.github.io/matchbox/?selectedKind=Feedback%7CBanner&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) needs the relevant `aria` role.

In this case, adding `role="alert"` to each banner will allow screen readers to encounter the content whenever these elements show up on the page, particularly when their rendering is dynamic.

**Comment by jonambas** [comment]
Should this be conditionally added depending on `props.status`? Or should all banners have this role?

**Comment by nicklemmon** [comment]
Well, it depends - are these always present when a view loads or do they ever render based on state changes?

If so, `role="alert"` should just always be there to be safe. If they aren't typically very dynamic, then maybe it isn't needed.

**Comment by jonambas** [comment]
Most are static, and rendered based on state at initial load. Would it help to post example use cases?

**Comment by jonambas** [comment]
Closing this – as part of the [UX-372](https://sparkpost.atlassian.net/browse/UX-372) epic, I'll make sure the Banner ticket includes AC that the component should allow a `role` prop to be passed through
