### ISSUE TITLE
For icons, consider leveraging the <use/> tag with a spritesheet to allow asset caching

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#211]
Inline SVGs are definitely the way to go for a modern icon set, particularly since they allow for styling of individual elements within an icon. That being said, inline each icon individually comes with a performance cost - the images are never cached since they are served as markup.

To get the best of both worlds, the `<use/>` element can be leveraged that then references an external spritesheet. Each icon in the spritesheet has a unique identifier that the `<use/>` tag then references. It's pretty neat!

Styling still works the same way as it does with a 'traditional' inline SVG as well. This approach is not supported in IE11, but at the moment, that doesn't appear to be a concern.

## Resources

* [SVG `use` with external source](https://css-tricks.com/svg-use-external-source/)
* [Webpack SVG Sprite Loader](https://github.com/kisenka/svg-sprite-loader)

**Comment by jonambas** [comment]
Closing this as our externally-sourced icon library can't easily be converted to a spritesheet. Maybe in the future when we have time to build our own!
