### ISSUE TITLE
The Toggle component label needs to be hidden for screen reader users and an alternative label needs to be a required prop

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#232]
<img width="396" alt="Screen Shot 2019-08-28 at 1 55 21 PM" src="https://user-images.githubusercontent.com/3613392/63880353-92b59b80-c99b-11e9-8734-2096b6ee1760.png">

When the keyboard encounters this content in the DOM, it is read as "Unchecked, On Off, checkbox".

## Possible Fix:

Wrap "On Off" in a `<span aria-hidden="true"></span>` and provide a way to pass in an alternate label that is specific to that particular `<Toggle/>` instance

For example:
```jsx
<Toggle label="Do Not Disturb"/>
```

**Comment by jonambas** [comment]
Closing - addressed in hibana
