### ISSUE TITLE
New Component - Multiple entry ComboBox component needed

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#259]
A new variant of the ComboBox is needed:

1. Allows entry of a series of data that is not populated from a dropdown (i.e., a series of email addresses)
1. Allows duplicate entry of the same content (i.e., two email addresses with the same content)
1. Allows for the removal of one of the items even if their content is duplicated. Should fix this scenario:

**Before hitting backspace:**

![Screen Shot 2019-10-08 at 10 12 04 AM](https://user-images.githubusercontent.com/3613392/66406837-48700300-e9ba-11e9-9c8b-448670acbc59.png)

**After hitting backspace 😟:**

![Screen Shot 2019-10-08 at 10 12 10 AM](https://user-images.githubusercontent.com/3613392/66406846-4ad25d00-e9ba-11e9-809d-aad06663d878.png)

**Comment by jonambas** [comment]
I think this might be an issue with your particular implementation. `ComboBox` doesn't actually handle entry removal.

Not sure what your wrapper looks like, but I think this would work:
- Use an object for each entry such as `{ email, key }`
- `itemToString` prop to render `email`
-  Filter by `key` in `removeItem`

I can write up a small example if you'd like

**Comment by nicklemmon** [comment]
I actually did implement something inside 2web2ui and was opening this issue to bring the component in to Matchbox. I'll get around to it sometime!

**Comment by jonambas** [comment]
Closing – since ComboBox will be deprecated
