### ISSUE TITLE
Hibana Select component does not render with passed in `maxWidth` styled-system prop

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#451]
## 🐛 Bug report

**Current Behavior**

- The `TextField` accepts `maxWidth` as a prop
- The `Select` component, however, does not appear to follow suit

**Expected behavior**

- Matchbox controls should accept the `maxWidth` prop consistently - or not at all!

**Reproducible example**

- in 2web2ui, checkout the branch `FE-1093` and go to `/alerts/create`
- _Here is a screenshot:_

<img width="1381" alt="Screen Shot 2020-06-04 at 10 35 06 AM" src="https://user-images.githubusercontent.com/3613392/83770619-47799900-a64f-11ea-9ca2-9d7450878ee1.png">

**Suggested solution(s)**

- Make props consistent between all Matchbox form controls

**Additional context**

- This is to address https://jira.int.messagesystems.com/browse/FE-1093

**Comment by jonambas** [comment]
This is actually a big bug, TextField is accepting all styled-system props 😓 . Fixing now
