### ISSUE TITLE
Need a way to handle Panel "header" UI with a border

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#467]
## 🚀 Feature request

**Current Behavior**
`Panel` supports passing in a `title` prop, which handles most scenarios, however, there are certain cases in which having a border below the title (along with a little bit of padding) would be nice. Here is an example:

**Before:**
<img width="656" alt="Screen Shot 2020-06-16 at 11 07 52 AM" src="https://user-images.githubusercontent.com/3613392/84792448-daa4be00-afc1-11ea-9e7d-2cdff414d888.png">

**After:**
<img width="623" alt="Screen Shot 2020-06-16 at 11 08 27 AM" src="https://user-images.githubusercontent.com/3613392/84792454-dd071800-afc1-11ea-9b35-09c25cbd70d6.png">

I accomplished this by doing the following:

```js
<Panel title="Message History">
  <Box paddingTop="1.25rem" border="400"/> // `paddingTop` value is funky to adjust for button height inside - otherwise an alignment problem is introduced!
</Panel>
```
**Desired Behavior**

Ideally, this could be handled through compound component composition.

**Suggested Solution**
```js
<Panel>
  <Panel.Header borderBottom="whatever"> // defaults to no border, but styled-system props could be exposed here
    <Panel.Title>Message History</Panel.Title>
  </Panel.Header>
</Panel>
```

**Who does this impact? Who is this for?**

Makes FE development easier and easier to understand.

**Comment by jonambas** [comment]
👍  Thanks, need this for sure

**Comment by tokonoma** [comment]
What if we had an optional prop on tables to include a border-top on the table header instead?

**Comment by nicklemmon** [comment]
> This is Tim
> What if we had an optional prop on tables to include a border-top on the table header instead?

I think it would be good to expose the `border` props on both the `Panel` and the `Table` - there have been spots where we have resorted to hacky CSS to remove borders and things in spots!

The `Panel.Header` would also address other scenarios too - for example:

```js
<Panel>
  <Panel.Header>
    <Panel.Title>My Title</Panel.Title>
  </Panel.Header>

  <Empty/>
</Panel>
```

Here is a screenshot of this sort of scenario in the app with what we have now that doesn't involve a table:
<img width="513" alt="Screen Shot 2020-06-17 at 12 54 43 PM" src="https://user-images.githubusercontent.com/3613392/84926749-db108800-b099-11ea-9a12-b7668d634752.png">

**Comment by jonambas** [comment]
@nicklemmon We want to make this change but it might not be until we release 4.1 with other component improvements ~ maybe a month from now. We're still working on a few things to wrap up 4.0.0.
