### ISSUE TITLE
The UnstyledLink component should support the `role` prop

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#540]
## 🚀 Feature request

**Current Behavior**

For Hibana only, `<UnstyledLink role="button"/>` does not successfully render to the DOM as `<a role="button"/>`.

**Desired Behavior**

I should be able to modify the `role` of a link while using Matchbox.

**Suggested Solution**

Pass on the value of the `role` prop to the rendered anchor tag.

**Who does this impact? Who is this for?**

This largely helps screen reader users when links open modals instead of navigating to new pages.

**Comment by jonambas** [comment]
Are you using a wrapper component by any chance? We pass through `role` but only if it (1) does not have a wrapper and (2) does not have an `onClick`. See: https://github.com/SparkPost/matchbox/blob/main/packages/matchbox/src/components/UnstyledLink/UnstyledLink.js#L12
