### ISSUE TITLE
Sizing value of 1250 does not work with styled-system props

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#566]
## 🐛 Bug report

**Current Behavior**

```
<Box maxWidth="1250"/>
```

This doesn't render the correct styled-system value.

**Expected behavior**

Using `maxWidth="1250"` _should_ output CSS equivalent to `max-width: 66rem`

**Suggested solution(s)**

Probably a configuration problem - the value doesn't appear to be output to https://design.sparkpost.com/design/tokenreference either

**Comment by jonambas** [comment]
@nicklemmon looks like the token you're looking for is `1350`? I believe we initially published `1250`, but was a typo and is now fixed. See https://github.com/SparkPost/matchbox/commit/593e8266f67817495296ae64cd246aba5630480a#diff-4e5bb8b5e9e7fc50d5f5876cc6696e6a

**Comment by nicklemmon** [comment]
@jonambas Nice! We are just a version behind for design tokens. I'll update accordingly.
