### ISSUE TITLE
Expose `border` styled-system props on the Expandable component

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#693]
## 🚀 Feature request

**Current Behavior**

As it stands, only `margin` styled-system props are passed to the `Expandable`.

**Desired Behavior**

Ideally, `border` props would be passed so nested `Expandable` instances within `Panels` would be possible. See mocks:
<img width="1211" alt="Screen Shot 2020-11-20 at 5 00 07 PM" src="https://user-images.githubusercontent.com/3613392/99854195-5ba84880-2b52-11eb-8d77-639fefd2dfb8.png">

**Suggested Solution**

Allow passage of `border` styled-system props.

**Who does this impact? Who is this for?**

Needed for SA epic currently in progress.

**Comment by jonambas** [comment]
See: https://matchbox-storybook.netlify.app/?path=/story/layout-expandable--borderless

**Comment by nicklemmon** [comment]
Nice, I'll close this one and open a ticket to add documentation to design.sparkpost.com.

Thanks, Jon.
