### ISSUE TITLE
Add a "variant" or "dark" prop to the LabelValue component

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#709]
## 🚀 Feature request

**Current Behavior**

The `LabelValue` frequently renders on a dark background - we can handle styling on our end, or this could be handled by a prop in Matchbox. I think the latter would be simpler.

**Desired Behavior**

Theming the `LabelValue` component should be controlled via a prop provided by Matchbox.

**Suggested Solution**
```js
<LabelValue dark />
```

or

```js
<LabelValue theme="dark"/>
```

or

```js
<LabelValue variant="dark" />
```

Or maybe none of these! There could be an API that works better than this.

**Who does this impact? Who is this for?**

This largely impacts our ability to consistently theme this component - and theme it between platforms.

**Comment by jonambas** [comment]
Closing this in favor of https://sparkpost.atlassian.net/browse/UX-429
I think we may go for something like `appearance="inverted"` to support dark mode in the future if we ever do that
