### ISSUE TITLE
Modal.Footer should render passed in child components without restrictions

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#710]
## 🚀 Feature request

**Current Behavior**

`Modal.Footer` only accepts `Button` components as children. In our app, we need to render links (usually that drive the router rather than true links) that _look like_ buttons but are semantically anchor tags:

**Desired Behavior**

The following should render successfully:
```js
<Modal.Footer>
  <PageLink as={Button}>Confirm Something</PageLink>
</Modal.Footer>
```

Unfortunately I think the only solution is to be less restrictive - I think as we have experimented with compound components in the app, that less restriction is ultimately better when it comes to handling children. I think this sort of a restrictive approach was something I had endorsed previously but now I'm not so sure.

See above.

Impacts FE engineers only, or may impact end users if a developer uses a non-ideal semantic element due to a component API restriction.

**Comment by jonambas** [comment]
I think, so existing modals don't break - we can append `children` if we find zero `Button`s

```js
// Modal.Footer
<Box display="flex" justifyContent="space-between">
  <Box>
    {buttons[0] && React.cloneElement(buttons[0], getButtonProps(0, buttons[0]))}
    {buttons[1] && React.cloneElement(buttons[1], getButtonProps(1, buttons[1]))}
  </Box>
    {buttons[2] && (
      <Box>{buttons[2] && React.cloneElement(buttons[2], getButtonProps(2, buttons[2]))}</Box>
    )}
 {!buttons.length && props.children}
</Box>
```
