### ISSUE TITLE
Update Label component API to accept the `htmlFor` prop rather than deriving its value from `id`

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#811]
## 🚀 Feature request

**Current Behavior**

```jsx
<Label id="my-label" />
```

Renders as:

```html
<label for="my-label" id="my-labelLabel" />
```

**Desired Behavior**

```jsx
<Label htmlFor="my-form-field" id="my-label" />
```

Renders as:

```html
<label for="my-form-field" id="my-label" />
```

**Suggested Solution**

Remove the derivation of the `htmlFor` prop and just pass the prop.

**Who does this impact? Who is this for?**

The current implementation causes a few problems:

- The API is confusing - the rendered DOM is surprising vs. the props passed in
- When using `downshift`, the `getLabelProps` method returned by `useCombobox` passes a value both for `htmlFor` and for `id` - this doesn't work with the current implementation of the component and causes some focus management/a11y bugs
- This _might_ block https://sparkpost.atlassian.net/browse/FE-1386

Thanks again 👋

**Comment by jonambas** [comment]
We can support both cases! In the pull request, I'm passing through `htmlFor` and `id` if both exists, otherwise defaulting to the previous behavior
