### ISSUE TITLE
The Button variant "outline" does not render the loading indicator via the "loading" prop

### ISSUE THREAD

**Issue by nicklemmon** [SparkPost/matchbox#820]
## 🐛 Bug report

**Current Behavior**

Button instances with a solid background show the loading indicator just fine. Buttons without a colored background do not!

**Expected behavior**

The loading indicator should assume the same color/fill of the Button instance text content.

**Reproducible example**

https://codesandbox.io/s/matchbox-v4-button-loading-bug-ln3lk

**Suggested solution(s)**

You may be able to leverage CSS `currentColor` to handle the color here.

**Comment by jonambas** [comment]
Trying to figure out what's going on here, they seem to work fine in Libby: https://matchbox-libby.netlify.app/?path=Button__loading&source=false
